export const RETELL_API_URL = process.env.REACT_APP_NEXT_PUBLIC_RETELL_API_URL;
export const RETELL_AGENT_ID = process.env.REACT_APP_NEXT_PUBLIC_RETELL_AGENT_ID;

export const INTERVIEW_ID = "ebf6eb61-595e-4efd-8126-918c27b4f094";